#!/bin/bash
# This is an example catalystrc. As such, it doesn't actually *do* anything.

# Uncomment the following to increase the number of threads used to compile.
export MAKEOPTS="-j{{ grains['num_cpus'] }}"
export EMERGE_DEFAULT_OPTS=" -v --jobs={{ grains['num_cpus'] }} "
export ACCEPT_LICENSE='*'
export I_KNOW_WHAT_I_AM_DOING=yes
